### ISSUE TITLE
missing modules in makefile

### ISSUE THREAD

**Issue by kimlop** [drupal-soda/soda-profile#6]
this is the error that I get when i try yo install from drush make command:
The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as sites/all/modules. Missing modules: Clone, Legal, Libraries, Restws, Token, Rdfui, Rdfx, Sparql, Sparql_endpoint, Sparql_registry, Dbee, Services, Services_definition, Services_entity, Services_oauth, Contentapi, Contentapi_summary, Rest_server, Anonymous_publishing, Anonymous_publishing_cl, Anonymous_publishing_lr, Anonymous_publishing_pet, Honeypot, Views, Views_bulk_operations, Views_data_export, Views_ui

**Comment by theodorosploumis** [comment]
Please, use the instructions from https://github.com/drupal-soda/soda-profile#installation. Also you can find all files on a complete Drupal installation at https://github.com/drupal-soda/soda-profile-full.
